name: nahawi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+8

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  animated_theme_switcher: ^2.0.10
  animated_toggle_switch: ^0.8.5
  another_xlider: ^3.0.2
  arabic_numbers: ^1.0.0
  archive: ^4.0.7
  awesome_notifications: ^0.10.0
  awesome_notifications_core: ^0.10.0
  badges: ^3.1.2
  bot_toast: ^4.1.3
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.0
  diacritic: ^0.1.6
  dio: ^5.8.0+1
  drift: ^2.26.1
  easy_url_launcher: ^0.0.7
  either_dart: ^1.0.0
  expansion_tile_card: ^3.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  flutter_slider_drawer: ^3.0.2
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  get: ^4.7.2
  get_it: ^8.0.3
  get_storage: ^2.1.1
  group_button: ^5.3.4
  hijri: ^3.0.0
  horizontal_stepper_step: ^0.0.5
  html: ^0.15.6
  http: ^1.4.0
  icons_launcher: ^3.0.1
  image: ^4.5.4
  infinite_scroll_pagination: ^4.1.0
  info_popup: ^4.3.2
  just_audio: ^0.10.2
  lottie: ^3.3.1
  # package_rename: ^1.10.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pie_menu: ^3.3.0
  read_more_less: ^1.0.1
  rxdart: ^0.28.0
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  stylish_bottom_bar: ^1.1.1
  url_launcher: ^6.3.1

# remove this line if you wish to build for iOS or macOS
  drift_flutter: ^0.2.4

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.21.0

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFE"
  image: assets/images/syntactic_logo240.png
  color_dark: "#181818"
  image_dark: assets/images/syntactic_logo240.png

  android_12:
    image: assets/images/syntactic_logo240.png
    icon_background_color: "#FFFFFE"
    image_dark: assets/images/syntactic_logo240.png
    icon_background_color_dark: "#181818"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/locales/
    - assets/svg/
    - assets/svg/hijri/
    - assets/icons/
    - assets/lottie/
    - assets/images/onboarding/
    - assets/images/
    - assets/json/collections.json
    - assets/json/books/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: kufi
      fonts:
        - asset: assets/fonts/Kufam-Regular.ttf
        - asset: assets/fonts/Kufam-VariableFont_wght.ttf
        - asset: assets/fonts/Kufam-Italic-VariableFont_wght.ttf
    - family: naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
package_rename_config:
  macos:
    package_name: com.alheekmahlib.nahawiapp.nahawi

flutter_assets:
  # assets_path: assets/lottie/
  assets_path: assets/svg/
  output_path: lib/core/utils/constants/
  # filename: lottie_constants.dart
  filename: svg_constants.dart
  field_prefix: null
  class_name: SvgPath

icons_launcher:
  image_path: "assets/images/syntactic_logo.png"
  platforms:
    android:
      enable: true
      image_path: "assets/images/syntactic_logo.png"
    ios:
      enable: true
      image_path: "assets/images/syntactic_logo.png"
    web:
      enable: false
      image_path: "assets/images/syntactic_logo.png"
    macos:
      enable: true
      image_path: "assets/images/syntactic_logo.png"
    windows:
      enable: false
      image_path: "assets/images/syntactic_logo.png"
    linux:
      enable: false
      image_path: "assets/images/syntactic_logo.png"
