name: syntactic
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  get: ^4.6.6
  animated_theme_switcher: ^2.0.9
  another_xlider: ^3.0.2
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  hijri: ^3.0.0
  flutter_slider_drawer: ^2.1.3
  arabic_numbers: ^1.0.0
  screenshot: ^2.1.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  flutter_screenutil: ^5.9.0
  stylish_bottom_bar: ^1.0.3
  expansion_tile_card: ^3.0.0
  device_info_plus: ^9.1.1
  http: ^1.1.2
  url_launcher: ^6.2.2
  info_popup: ^4.3.1
  lottie: ^2.7.0
  pie_menu: ^3.1.3
  just_audio: ^0.9.36
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  objectbox: ^2.4.0
  objectbox_flutter_libs: any
  diacritic: ^0.1.5
  group_button: ^5.3.3
  image: ^4.1.3
  horizontal_stepper_step: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  objectbox_generator: any


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/locales/
    - assets/svg/
    - assets/svg/hijri/
    - assets/icons/
    - assets/lottie/
    - assets/images/onboarding/
    - assets/json/bookName.json
    - assets/json/poems/0.json
    - assets/json/poems/1.json
    - assets/json/books/0.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: kufi
      fonts:
        - asset: assets/fonts/Kufam-Regular.ttf
        - asset: assets/fonts/Kufam-VariableFont_wght.ttf
        - asset: assets/fonts/Kufam-Italic-VariableFont_wght.ttf
    - family: naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
